name: Build CMC Privacy Feed (Warsaw)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6,12,18 * * *'  # קיץ (CEST) -> 08/14/20 בוורשה
    - cron: '0 7,13,19 * * *'  # חורף (CET) -> 08/14/20 בוורשה

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Quick API ping (quotes) – debug
        env:
          CMC_API_KEY: ${{ secrets.CMC_API_KEY }}
        run: |
          set -e
          echo "Testing CMC quotes/latest…"
          curl -s -H "X-CMC_PRO_API_KEY: $CMC_API_KEY" \
            "https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest?symbol=PIVX&convert=USD,BTC" \
            -D /tmp/headers.txt -o /tmp/resp.json || true
          echo "=== Response headers (last lines) ==="
          tail -n 20 /tmp/headers.txt || true
          echo
          echo "=== Response body (first 400 chars) ==="
          head -c 400 /tmp/resp.json || true
          echo

      - name: Build latest.json
        env:
          CMC_API_KEY: ${{ secrets.CMC_API_KEY }}
        run: python build_feed.py

      - name: Commit feed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add latest.json || true
          git commit -m "Update feed $(date -u +'%Y-%m-%d %H:%M UTC')" || echo "Nothing to commit"
          git push || true
