name: Build CMC Privacy Feed (Warsaw)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6,12,18 * * *'  # קיץ (CEST, UTC+2) -> 08/14/20
    - cron: '0 7,13,19 * * *'  # חורף (CET, UTC+1) -> 08/14/20

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Quick API ping (quotes) – debug
        env:
          CMC_API_KEY: ${{ secrets.CMC_API_KEY }}
