name: Build CMC Privacy Feed (Warsaw)

on:
  schedule:
    # קיץ (CEST, UTC+2): 08/14/20 -> 06/12/18 UTC
    - cron: "0 6,12,18 * * *"
    # חורף (CET, UTC+1): 08/14/20 -> 07/13/19 UTC
    - cron: "0 7,13,19 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Show environment (debug)
        run: |
          python -V
          ls -la
          echo "Has secrets? -> ${{ secrets.CMC_API_KEY != '' }}"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Build latest.json
        env:
          CMC_API_KEY: ${{ secrets.CMC_API_KEY }}
        run: |
          python build_feed.py

      - name: Commit feed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add latest.json || true
          git commit -m "Update feed $(date -u +'%Y-%m-%d %H:%M UTC')" || echo "Nothing to commit"
          git push || true
